### ISSUE TITLE
Websocket connection - html

### ISSUE THREAD

**Issue by Shrest** [perrygeo/pi_sensor_realtime#1]
Hi,
    I installed websocketd on my RPi and struggling with connecting on web socket through a html page. The html code used is given below:
![html_ws](https://cloud.githubusercontent.com/assets/8669694/10562270/df3116f2-7570-11e5-8601-a1e265ec3d66.jpg)

I can see the html content, but there is no connection established on web socket. am I missing something here?

**Comment by perrygeo** [comment]
Does your browser's javascript console show any errors? 

I would guess that rpi_ipaddress:8080 is unreachable from the client machine. This could be due to either network issues (firewall, dns, etc) or the websocket server may not actually be running, or running on a different port. Hard to say without seeing your whole setup.

Have you tried the [websocketd quickstart](https://github.com/joewalnes/websocketd#quickstart)? Once you get that working, try running the same basic example but with the websocket server on the raspberry pi instead of localhost. That should provide some useful clues.

**Comment by Shrest** [comment]
I did some investigation and found that the issue is "$". I get the following error in the console.
"Uncaught ReferenceError:$ is not defined." 

Websocketd is working as I can see if I take "var ws = new WebSocket(....)" out of $function().

**Comment by Shrest** [comment]
Hi,
   The issued is resolved, once I reloaded the jQuery library file. Great to see the data on the web page. Thanks a lot for your time.
